0.5 301.2316819315631
0.7435897435897436 233.92117081701355
0.9871794871794872 197.5443638039907
1.2307692307692308 179.3760809771589
1.4743589743589745 166.14672089051382
1.7179487179487178 153.47837814792587
1.9615384615384615 149.158115729183
2.2051282051282053 141.26011538989576
2.448717948717949 137.3613692587549
2.692307692307692 135.15136810798901
2.9358974358974357 127.64292016900734
3.1794871794871793 127.94430333066595
3.423076923076923 126.06728876848159
3.6666666666666665 123.48109072670506
3.91025641025641 120.28509848504929
4.153846153846153 117.21335226071317
4.397435897435898 120.23698270856292
4.6410256410256405 116.78647330096413
4.884615384615384 113.18726989708311
5.128205128205128 112.82218955946804
5.371794871794871 112.49074122414346
5.615384615384615 114.59088228512668
5.858974358974359 111.98207439159536
6.102564102564102 109.32281566300365
6.346153846153846 110.12121728518476
6.589743589743589 110.47621481358792
6.833333333333333 105.69999779833174
7.076923076923077 106.21550134862447
7.32051282051282 108.93695747501658
7.564102564102564 106.3044026179944
7.8076923076923075 104.01443111211314
8.051282051282051 104.8107301803673
8.294871794871796 103.34357515144654
8.538461538461538 103.31127089691132
8.782051282051281 101.33550530881425
9.025641025641026 104.46676074695164
9.269230769230768 102.13029039897059
9.512820512820513 105.80102034718143
9.756410256410255 103.06764837075092
10.0 103.33428963497364
Traceback (most recent call last):
  File "/home/Student/s4606685/31_1_22/weight_Script.py", line 115, in <module>
    plt.plot(lambda_vals[0:24],cumerrlist)
  File "/home/Student/s4606685/torch/lib/python3.9/site-packages/matplotlib/pyplot.py", line 3019, in plot
    return gca().plot(
  File "/home/Student/s4606685/torch/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 1605, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/home/Student/s4606685/torch/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 315, in __call__
    yield from self._plot_args(this, kwargs)
  File "/home/Student/s4606685/torch/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 501, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (24,) and (40,)
